---
# tasks file for user_creation
- user: 
    name: '{{ myuser }}'
    comment: "user1"
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    state: present

- name: multiple users
  user: 
    name={{item}} 
    state=present
    shell=/bin/bash
    generate_ssh_key=yes
    ssh_key_bits=2048
    ssh_key_file='.ssh/id_rsa'    
  with_items:
    - testuser1 
    - testuser2 
    - testuser3    
  loop_control:
    label: "{{item}}"
