---
# tasks file for user_creation
- user: 
    name: '{{ myuser }}'
    comment: "user1"
    shell: /bin/bash
    generate_ssh_key: yes
    ssh_key_bits: 2048
    ssh_key_file: .ssh/id_rsa
    state: present
    uid: 1001

- name: multiple users
  user: 
    name="{{item.name}}" 
    state=present
    shell=/bin/bash
    generate_ssh_key=yes
    ssh_key_bits=2048
    ssh_key_file='.ssh/id_rsa'
    uid="{{item.uid}}"    
  with_items:
    - name: 'testuser1'
      uid: 10001 
    - name: 'testuser2'
      uid: 10002
    - name: 'testuser3'
      uid: 10003
  loop_control:
    label: "{{item.name}}"
